### ISSUE TITLE
Is possible to add BetterTweetdeck to Tweeten?

### ISSUE THREAD

**Issue by Revod** [MehediH/TweetenSite#100]
Could be amazing or at least add the https://github.com/eramdam/BetterTweetDeck featured that show the thumbnail for external websites like imgur, instagram, etc. Is possible to inject in electron the .js files and other required to make it work in Tweeten? 

Cheers,
Revod

**Comment by MehediH** [comment]
We can't do that because the license for BetterTweetDeck doesn't allow it. We will have to make our app open source if we wanted to use their code.

________________________________
