### ISSUE TITLE
Memory leak and full CPU usage

### ISSUE THREAD

**Issue by Crackmort** [MehediH/TweetenSite#101]
Hi,
I have a i5 4670k @4.4GHz and 16Go of RAM.

For the second time, Tweeten use so much RAM and CPU for no reason, I don't know how to help to solve the problem, so I link all I can found.
It make my PC so laggy, I have to restart Tweeten to solve the problem.

Here the screen shot of CPU/RAM using.
![ss 2016-12-22 at 12 58 22](https://cloud.githubusercontent.com/assets/24716183/21425097/56e00f4e-c847-11e6-9633-93d26353206e.png)

The console message:
`D:\Programmes\Tweeten\resources\atom.asar\common\api\lib\deprecate.js:98(electron) ipc module is deprecated. Use require("electron").ipcRenderer instead.`

And here is the differents profiles that can be created to snapshot from the console:

http://www.mediafire.com/file/mssx2at29it9n51/Snapshots.zip

I have a little issue too, each time I launch Tweeten (It's from the two last update, I think), the console open too. Not really important but just boring to close it everytime.

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
