### ISSUE TITLE
[bug?] Column width setting

### ISSUE THREAD

**Issue by pighair** [MehediH/TweetenSite#102]
There is an option for column width in Setting menu which can be accessed by gear icon on nav menu, with following options "Narrow", "Medium" and "Wide".
But if I change this option, tweet height varies instead of width.
I took screenshots for this.

And it seems column width option is moved to the setting menu which can be accessed by "Tweeten" menu.

Using 3.3.2 beta on macOS Sierra 10.12.2.

![scr 2016-12-30 21 22 28](https://cloud.githubusercontent.com/assets/18534209/21565027/26412fc2-ced6-11e6-8732-452b4557327e.png)
![scr 2016-12-30 21 22 22](https://cloud.githubusercontent.com/assets/18534209/21565028/267d4caa-ced6-11e6-84fb-e1f0fa2c1f79.png)
![scr 2016-12-30 21 22 15](https://cloud.githubusercontent.com/assets/18534209/21565029/26806f98-ced6-11e6-9ea2-5ee9b0c9619b.png)

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
