### ISSUE TITLE
[bug] Error if I close app while setting window is opened.

### ISSUE THREAD

**Issue by pighair** [MehediH/TweetenSite#103]
Tweeten version: 3.3.2 beta for Mac
OS version: macOS Sierra 10.12.2

Step to reproduce:

1. Open Tweeten
2. Open Setting menu from the Tweeten menu next to Apple menu.
3. Activate main window
4. Close app by pressing Cmd+Q. It closes main window only. Setting menu is alive.
5. Press Cmd+Q again. Then you can see this error window.
![scr 2016-12-30 21 29 07](https://cloud.githubusercontent.com/assets/18534209/21565114/413112ec-ced7-11e6-8b74-ee9987811ec4.png)

Cmd+Q should close all window and quit app.

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
