### ISSUE TITLE
Tweeten is using 31% of my CPU....?

### ISSUE THREAD

**Issue by LewisHolt** [MehediH/TweetenSite#104]
I'm very new to Tweeten and so far I'm not impressed. It seems slow to load, lags when loading some tweets and it keeps reverting back to the tiny columns when I set the width of it to be so much wider.

It's also using 31% of my CPU which is annoying. :/ I do have a question though, Tweeten doesn't try to load the entire history of a DM group does it? I'm in one that's at least a year old with daily active chatters and Tweeten seems to have issues around that DM group. :/

I'll be disabling Tweeten for now, I've heard you guys are doing a brand new version for 2017 so I'll check that out.

**Comment by MehediH** [comment]
I have made a bunch of improvements to Tweeten's performance and resource usage. Please try out Tweeten 2 later this week and you should see some major improvements.
