### ISSUE TITLE
"Download Started" appears two times

### ISSUE THREAD

**Issue by Spidersouris** [MehediH/TweetenSite#106]
When you right click on a GIF, click on the "Save GIF" button, close the popup and click on the "Save GIF" button again, the "Download Started" text will appear two times in the popup.

Here's what it looks like normally:

![Preview](https://puu.sh/tqOvb/dc8925d631.png)

Here's what it looks like when the "Save GIF" button is clicked two times:

![Preview](https://puu.sh/tqOwi/d8f6ded8dc.png)

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
