### ISSUE TITLE
Application freezing when receiving notifications

### ISSUE THREAD

**Issue by HakenBrowning** [MehediH/TweetenSite#107]
(I see this is "TweetenSite" GitHub, but the Bug report option of the applications redirects here so... I dunno ?)

System : Windows 10 Pro N x64 with Media Feature Pack enabled (so it's the same as a non-N version in theory)
I love Tweeten, and I use it since the beginning. But on my new PC, each time I receive a notification, the application (either the standalone version and the Windows Store version) freeze for quite some time (one minute, maybe a little more) after the notification goes. And it repeats until I have no notifications left, which can take some time (I'm using Twitter a lot). On my old laptop (Windows 10 Pro non-N x64), I have absolutely 0 problem.
I dunno if there are logs for this application, and I didn't find one.

**Comment by HakenBrowning** [comment]
Still hoping someone sees this, so I'll share what I know : when I deactivated Windows notifications for Tweeten, it stopped freezing. So it really is because of them. But I can't be sure if it's the notification system or the sound.

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
