### ISSUE TITLE
[Bug?] Unknown white frame will be displayed

### ISSUE THREAD

**Issue by mfmfneko** [MehediH/TweetenSite#109]
OS: Windows10 Pro (64bit)
Tweeten version: 3.3.3

P.S: I'm using dark theme.
![](https://cloud.githubusercontent.com/assets/9716543/23367278/06258422-fd4d-11e6-8ef8-1c4ffffc8b46.png)

**Comment by MehediH** [comment]
Fixed, check for updates.

**Comment by mfmfneko** [comment]
I really appreciate you.
