### ISSUE TITLE
Tweeten v3.3.4 unexpectedly quits

### ISSUE THREAD

**Issue by rg144** [MehediH/TweetenSite#110]
Hi guys,

Am noticing Tweeten v3.3.4 unexpectedly quits (intermittently), when open in the background.
Build 0.1.170227-2000 running Win10 x64

No Console Errors in dev tools, but 1 warning:

![image](https://cloud.githubusercontent.com/assets/25413997/23601260/afcb53fc-029e-11e7-8700-3cd75f661f2a.png)

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
