### ISSUE TITLE
[Request]Use old replay style with @s (and remove in reply to @s)

### ISSUE THREAD

**Issue by Garry050** [MehediH/TweetenSite#114]
Use old replay style (with @s) isn't old replay style. please remove[in reply to @s]
<img src=https://i.ppn.pw/cc/645ca6c4/l2c14acfc.png>

**Comment by Garry050** [comment]
wait, wtf?
**Resetting columm size when playing video(example:YouTube) in tweeten.**
I can not reproduce it now, is this a coincidence ...? nvm... sorry

Renamed Titile, [Request]Use old replay style with @s (and remove in reply to @s)

**Comment by MehediH** [comment]
Can you please explain the issue with the reply style?

**Comment by Garry050** [comment]
Old style isn't using [in reply to @s].
Can you remove it?

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
