### ISSUE TITLE
On some videos I get the message 'this media could not be played'

### ISSUE THREAD

**Issue by manderley3** [MehediH/TweetenSite#115]
On some ( I would now say all as bbc videos and others not working) videos I get the message 'this media could not be played'
When I click on 'view original' I am taken to twitter in my browser and the video plays.  But it does not play in Tweeten for some reason.  Why does this happen is it a Tweeten issue, are other people having this issue?
Is this something Tweeten need to fix?
![tweeten1](https://user-images.githubusercontent.com/20576484/27050099-42ec6b1a-4fa9-11e7-9cb5-206c617b17e6.png)

**Comment by nykoo** [comment]
same for me but in all media video...

**Comment by manderley3** [comment]
I have found that it is all videos not working also.

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
