### ISSUE TITLE
Add ability to copy link to tweet

### ISSUE THREAD

**Issue by bc3tech** [MehediH/TweetenSite#20]
Tweetdeck has ability to right click the timestamp and get a link to the tweet. Nowhere in Tweeten am I finding this capability.

**Comment by spartibus** [comment]
I would also like to request you add this functionality to not only tweet timestamps, but also to images and account names.

**Comment by bc3tech** [comment]
@spartibus : eh... i'd be more a fan of replicating what Tweetdeck offers... it doesn't do it for account names or images (that I recall) does it?

**Comment by spartibus** [comment]
@bc3tech Yes, what I requested is also what Tweetdeck did (at least on the desktop application; I can't speak to the web app).

**Comment by RheingoldRiver** [comment]
Yeah tweetdeck had basically a general "copy link location" functionality.

I'd settle for only having it able to copy the location of a tweet, though, that's by far what I used it for the most

**Comment by MehediH** [comment]
Added with Tweeten 3.0 https://blog.tweeten.xyz/tweeten-3-0-save-gifs-drag-and-drop-copy-urls-and-more-fa0a9e623790#.cjj1pfnmu
