### ISSUE TITLE
Not remembering monitor it was opened on

### ISSUE THREAD

**Issue by Stanzilla** [MehediH/TweetenSite#3]
Starting with 1.6 and now 1.7, Tweeten does not longer remember the monitor it was opened on.

I always have it on display 2 and when I close and reopen it opens on display 1.

**Comment by MehediH** [comment]
It seems to be working for me with Tweeten 1.8. Can you check?

Windows: tweeten.xyz/windows
OS X: tweeten.xyz/osx

**Comment by Stanzilla** [comment]
Nope, not working. Do you have the window maximized?

**Comment by MehediH** [comment]
Heh, that's a weird bug. We will try to fix soon.

**Comment by Stanzilla** [comment]
Fixed in 3.1!
