### ISSUE TITLE
When restoring from tray, application doesn't remember maximizing

### ISSUE THREAD

**Issue by xKairu** [MehediH/TweetenSite#35]
I'm on Windows 10. I always have Tweeten maximized to fit all my columns, so I tried out the minimize to tray, and upon clicking the tray icon, Tweeten restores to just a small window rather than remembering I had it maximized.

Demo here: https://i.imgur.com/ND9hEXp.gifv

**Comment by MehediH** [comment]
Fixed with 3,1 https://t.co/X0pJSTbteg
