### ISSUE TITLE
[Feature Request] Color the "new message" or "new content" indicators at the sidebar

### ISSUE THREAD

**Issue by jonkyr** [MehediH/TweetenSite#36]
Really important, for example i use dark theme and white indicator of i.e. a new DM on the black and white icon of the sidebar doesn't really work well.

**Comment by MehediH** [comment]
Added with 3.0 https://blog.tweeten.xyz/tweeten-3-0-save-gifs-drag-and-drop-copy-urls-and-more-fa0a9e623790#.cjj1pfnmu
