### ISSUE TITLE
Tray icon doesn't hold in its place 

### ISSUE THREAD

**Issue by EmuAGR** [MehediH/TweetenSite#37]
OS: Windows 7 x64
Version: 1.9.1 beta

Replication:
- Minimize to tray, the icon is shown at the left side temporally, then hides in the hidden icons panel.
- Move the tray icon to its intended place, not hidden (I made sure it's marked as "shown" in the tray bar properties).
- Restore Tweeten (window size bug mentioned elsewhere), the icon vanishes from tray.
- Minimize to tray again.

Expected behavior: The icon keeps the place it was previously moved to.
Current behavior: The icon is shown at the left side temporally, then hides in the hidden icons panel.

Bonus: It would be sweet if the icon didn't vanish when not minimized, like other apps. It's prone to click mistakes and also distracting.

**Comment by MehediH** [comment]
Fixed with 3,1 https://t.co/X0pJSTbteg
