### ISSUE TITLE
Mac: X button in top left window corner quits the app, instead of just closing the window

### ISSUE THREAD

**Issue by davort** [MehediH/TweetenSite#39]
![image](https://cloud.githubusercontent.com/assets/1573304/14822328/885b0924-0bce-11e6-9a61-b40d2cb12eb5.png)

On Mac OS, hitting the red, X button (leftmost in the screenshot), should only close the app window, and not quit the app, as it is customary on Windows OS, and as what happens currently with Tweeten for Mac.

**Comment by MehediH** [comment]
Is the X button supposed to minimize the app on OS X?
