### ISSUE TITLE
Performace Lag

### ISSUE THREAD

**Issue by PicassoGoon** [MehediH/TweetenSite#44]
Whenever I run the app, which is every moment of my free time, I experience severe lag.
Anything I do within the app takes a lot of time to achieve, and once completed it takes 10x the amount of time to ready itself for the next task... very laggy and unresponsive... Its now at the point where I can only use tweeten, to watch my feeds, any interaction is painful... 
I have also noticed running this app affects the performance of anything else I might be running simultaneous...
Which leads me to believe this is a memory issue... now I have 4GB of ram, My system may not be cutting edge, but its no slouch either

Is this issue commonplace or am I the only one?

**Comment by Spidersouris** [comment]
I had the same problem (#42) but this morning I started Tweeten and it works perfectly, without any update or anything, that's pretty weird :stuck_out_tongue: 
Is it fixed for you too?

**Comment by Spidersouris** [comment]
Well, performance lags are here again in the last update...
