### ISSUE TITLE
[Feature Request] Have a little "copy image URL" button on enlarged images...

### ISSUE THREAD

**Issue by Duke-Igthorn** [MehediH/TweetenSite#47]
Since the right click menu doesn't work with copy etc. it would be really cool to easily gain access to a tweet's image URL as well as the entire tweet's URL.
This could be a little button in the enlarged view for instance. 
So far getting any URLs requires to open the tweet in a browser and manually copying from there which is an unneeded hassle.
<3

**Comment by spartibus** [comment]
https://github.com/MehediH/TweetenSite/issues/20

**Comment by MehediH** [comment]
Added with 3.0 https://blog.tweeten.xyz/tweeten-3-0-save-gifs-drag-and-drop-copy-urls-and-more-fa0a9e623790#.cjj1pfnmu
