### ISSUE TITLE
@user, Alert - Desktop notifications don't show up

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#51]
I have set several @user columns setup for Alert, Desktop notifications but they don't show up.

**Comment by RonnyTNL** [comment]
Setting Audio alert seems to create a sound on the arrival of a new tweet on the Home column.

Windows version, Win8.1 x64

**Comment by MehediH** [comment]
This isn't supported properly yet. Open tweetdeck.twitter.com on Chrome, enable Desktop Notifications, Allow Permission and it should work on Tweeten too.
