### ISSUE TITLE
@User colums don't 'update' the content, only the first Home column is automatically updated/refeshed

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#52]
@User colums don't 'update' the content, only the first Home column is automatically updated/refeshed
In tweetdeck those would all update around the time new tweets arrived.

Windows version on Win8.1 x64

**Comment by MehediH** [comment]
@RonnyTNL It's a TweetDeck issue, please contact Twitter Support regarding that.
