### ISSUE TITLE
Tweeten for Windows x64 does not terminate all processes on closure of the application

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#53]
On my Win8.1 x64 system only 2 out of 5 tweeten.exe processes exit when I close the application.
Watching it with sysinternals process explorer it only marks the 2 processes that close 'red' when the get the termination call.

The following command-lines stay behind.
"C:\Program Files\Tweeten\tweeten.exe" 

"C:\Program Files\Tweeten\tweeten.exe" --type=gpu-process --channel="1768.0.1753435434\1289972514" --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=2,23,51 --gpu-vendor-id=0x8086 --gpu-device-id=0x0416 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=10.18.14.4112 /prefetch:822062411

"C:\Program Files\Tweeten\tweeten.exe" --type=renderer --no-sandbox --lang=en-US --app-user-model-id=Tweeten --node-integration=true --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --channel="1768.2.1536141389\612851592" /prefetch:673131151

**Comment by MehediH** [comment]
@RonnyTNL This has been fixed.

**Comment by RonnyTNL** [comment]
Thanks very much, confirmed fixed!
