### ISSUE TITLE
RFE - Retweet transparency - current setting is nearly black on retweet arrow 

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#54]
Would it be possible to make the re-tweet overlay a bit more transparent.
The current setting almost shows black on green arrow, and the original image is hardly visible
(Using light theme).

Windows, Win8.1.

**Comment by MehediH** [comment]
You can disable the overlays by going into the settings. Just right click anywhere in the app and then click on settings.

**Comment by RonnyTNL** [comment]
Hi Thanks for the reply.
I do like the feature, I was just wondering if it could be a bit more transparent.
I have switched back to the old style "Enable classic style for Like and RT icons".
