### ISSUE TITLE
Tweeten 'Settings' windows does not close on clicking 'Done' button

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#55]
The Tweeten settings dialog does not close/disappear when pressing the 'Done' button.

A cosmetic issue, the Done button does not really stand out being black on black.
Other buttons show blue on black.

Windows version on Win8.1

**Comment by Stanzilla** [comment]
Agree, rename "Done" to "Apply" and add "OK" to apply and close?

**Comment by RonnyTNL** [comment]
That is an option.

But the settings you enter on the left bar (gear icon -> settings) If you press 'Done' there it applies and closes the dialog window. If you apply the same logic to the right mouse / settings then I would have expected this Tweeten settings dialog to also behave the same. (Press Done saves settings and close dialog window). Does that make sense?

**Comment by Stanzilla** [comment]
Yes

**Comment by MehediH** [comment]
Added with 3.0 https://blog.tweeten.xyz/tweeten-3-0-save-gifs-drag-and-drop-copy-urls-and-more-fa0a9e623790#.cjj1pfnmu
