### ISSUE TITLE
Missing collapsed Tweets

### ISSUE THREAD

**Issue by mmasnick** [MehediH/TweetenSite#59]
In Tweedeck it collapses long columns of tweets with a "show more" link
![show more](https://cloud.githubusercontent.com/assets/19934997/16052238/2d877288-3218-11e6-839a-b7b3a31af333.png)
In Tweeten, as far as I can tell, it just completely disappears the "show more" link AND with it, all of those tweets.  So it effectively deletes a lot of tweets if you're scrolling backwards.

My ideal solution would be if Tweeten could get rid of Tweetdeck's decision to collapse all those tweets, and instead to actually show all the tweets, but I don't know if that's possible.  Absent that, at the very least, Tweeten should show the "show more" link so that those of us who try to read all tweets in certain columns can continue to do so.
 
Thanks.

**Comment by manderley3** [comment]
This is an issue for me also it is not good that tweeten misses out tweets. because every morning I scroll back through tweets to where I left of the night before and find that a lot of tweets are missing. I hope tweeten will fix this issue.

**Comment by manderley3** [comment]
scrolling down, back through time of a few hours and when scroll back up to read the tweets I notice that tweets have disappeared, reload page tweets reappear.

**Comment by mmasnick** [comment]
A bit disappointing that there have been no updates or acknowledgements on this.  It seems like a fairly big bug.  The app shouldn't make tweets disappear like that.

**Comment by manderley3** [comment]
Agreed,  I have had to stop using tweeten for the moment because of this and had to go back to using tweetdeck.  I hope that this issue will be fixed soon so that I can use tweeten again.

**Comment by MehediH** [comment]
Sorry about this guys. Last time I tried the Show More button, it did nothing for me apart from hiding the button on TweetDeck. Does it actually work? If so, I will bring it back.

**Comment by manderley3** [comment]
Hi, Thanks for contacting. The Show More button does work on TweetDeck.

**Comment by mmasnick** [comment]
Yes, the "show more" button *absolutely* does work on Tweetdeck.  There are some cases where it presents it when it should not -- and then it just disappears, but that's maybe 1 out of every 20 times. 

Again, my *preference* would be that you could figure out a way to have Tweeten actually show all the tweets so that the "show more" isn't even needed at all.  If you could figure out a way to do that, it would make Tweeten *brilliant*.  But at the very least, the "show more" should be there.

**Comment by MehediH** [comment]
I am still trying to add this back to the app. I need to find the HTML class attached to the button, so that I can make it show up once again. Will take some time though.

**Comment by MehediH** [comment]
Hey guys, we are bringing this today. Look out for a new update later today! :)

**Comment by HoopBall** [comment]
Getting the app to show all tweets without Read More would gain a lot of fans. It's a huge complaint for Tweetdeck users and makes everything a scrolling mess.
