### ISSUE TITLE
Program opens as if 2nd screen was attached

### ISSUE THREAD

**Issue by Stoney35** [MehediH/TweetenSite#60]
I use a laptop and occasionally have a 2nd monitor attached to it. Since using Tweeten on the 2nd monitor, it opens as if there is a 2nd monitor attached, making it impossible to use. I attempted to use the 2nd screen and moving it onto my main screen but that didn't fix the issue.
I use windows 10, I try and keep programs updated (as i cant open Tweeten, i cant update it)

**Comment by Stoney35** [comment]
Uninstalling did not fix the issue

**Comment by MehediH** [comment]
@Stoney35 Does the issue still occur?
