### ISSUE TITLE
Application hangs for N (~4-5) seconds after certain interactions

### ISSUE THREAD

**Issue by koobs** [MehediH/TweetenSite#62]
The application appears to hang for 4-5 seconds, precluding all interaction, for the following actions:
- After clicking close [x] after viewing @profile or image previews
- When clicking links

The symptom is most easily noticeable when there is an animated image (gif) visible in the application window when this occurs.

If a video of the issue is required, please let me know

OS: Windows 7 x64
Tweeten: 01.160617-2000 (btw, can we switch to x.y.z semantic versions please :])

**Comment by manderley3** [comment]
I would agree it does hang at times and feels a bit clunky and jumpy at times to do with the hanging for a few seconds at times I guess.

**Comment by MehediH** [comment]
Do you possibly have Twitter Cards integration enabled?

**Comment by manderley3** [comment]
As far as I know I do not have Twitter Cards Integration enabled.  Not something I have come across.

**Comment by MehediH** [comment]
Are you running the latest version of Tweeten?

**Comment by koobs** [comment]
@MehediH I'm almost entirely sure I do not

**Comment by manderley3** [comment]
Yes running latest version of tweeten

**Comment by rdohms** [comment]
I have noticed the same with latest version and using twitter cards integration.

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
