### ISSUE TITLE
Background size on OSX, Chrome and Edge pages

### ISSUE THREAD

**Issue by ajaykarwal** [MehediH/TweetenSite#66]
The background on the OSX, Chrome and Edge pages does not cover the full window on large screens - I have a 27" Dell screen.

It's fine on the Windows page.

See screenshot

![screenshot_1](https://cloud.githubusercontent.com/assets/1458017/16799650/d05a3e68-48e9-11e6-80e7-5d39d9129271.png)

**Comment by MehediH** [comment]
Working on a new website right now, so don't wanna fix this. Thanks for the report though.
