### ISSUE TITLE
[BUG] Horizontal scroll bar at the bottom of new tweet window

### ISSUE THREAD

**Issue by EmuAGR** [MehediH/TweetenSite#67]
This didn't happen in <3.1 version. It appears just above the "Stay open" checkbox.

Version: 3.1 x64
SO: Windows 7 x64

Thank you!

**Comment by MehediH** [comment]
Will fix, thanks!

**Comment by MehediH** [comment]
Fixed - https://github.com/MehediH/TweetenSite/releases/tag/3.1.1-beta
