### ISSUE TITLE
[BUG] Tweeten Window ignoring keyboard input when clicking in from out of focus

### ISSUE THREAD

**Issue by spartibus** [MehediH/TweetenSite#70]
With the new release of 3.1.1 (0.1.160801-1900), whenever clicking into Tweeten to give it focus, it will not accept keyboard input, such as Escape to close images/windows, or 1, 2, 3 etc to change columns, or arrow keys to change images. What fixes this is clicking once more into the Tweeten window, and then keyboard input is accepted as would normally be the case.

So to be clear: 1 click to give Tweeten focus will not allow it to accept keyboard input, but two clicks into the Tweeten window does.

This behavior was not present until the update that came out todayish.

I tried reinstalling the latest version of 64bit Tweeten (I think i was on 32bit before) but it did not solve the issue.

I'm on Windows 10 x64.

**Comment by MehediH** [comment]
This has been fixed, look out for a new update later today.
