### ISSUE TITLE
Windows: Tweeten crashing my video driver

### ISSUE THREAD

**Issue by MunifiSense** [MehediH/TweetenSite#72]
Since Tweeten 3.1, my video driver has been crashing randomly with Tweeten open. If I go back to an older version this doesn't happen.

**Comment by MehediH** [comment]
@MunifiSense  There should be a new update out tomorrow, please try that and let me know if that fixes it.

**Comment by MehediH** [comment]
@MunifiSense Can you try now https://twitter.com/TweetenApp/status/767698126085980161
