### ISSUE TITLE
Polls are broken

### ISSUE THREAD

**Issue by snowbound** [MehediH/TweetenSite#73]
Polls are broken in 3.2.0. If I click on a post with a poll it displays the actual poll in the app but when I click on an item it for some reason opens up a Windows Explorer window here in Windows 7 Pro.

If I use Tweetdeck web it redirects me to Twitter.com page via a link to show me the choices and allows me to vote.

**Comment by MehediH** [comment]
@snowbound Do you have Twitter Cards enabled in Tweeten Settings?

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
