### ISSUE TITLE
Tweeten 3.3 calls directly to https://giphy.com/ doesn't honor proxy settings

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#74]
Tweeten 3.3 calls directly to https://giphy.com/ doesn't honor proxy settings.

**Comment by MehediH** [comment]
What do you mean?

**Comment by RonnyTNL** [comment]
My system uses a proxy to access internet, after the upgrade from 3.2 to 3.3 there is extra traffic that does not use the proxy to access the internet, the traffic is going towards the giphy.com server.
So I assume it has something to do with the added GIF feature. As this is not allowed the traffic is dropped.

Other connections to e.g. pbs.twimg.com work nicely via the proxy, so I would have expected the call to giphy.com also to be done over the system proxy.

**Comment by MehediH** [comment]
Not sure how we can fix this unfortunately. The feature just calls the Giphy API, nothing else.

**Comment by RonnyTNL** [comment]
So it's not the same code as which opens sockets to these sites? (these load nicely via proxy).

http://tweeten.xyz
tweetdeck.twitter.com
api.twitter.com
pbs.twimg.com
img.youtube.com
