### ISSUE TITLE
[Feature Request] Easier Access to Clear Button and "Clear All" Button

### ISSUE THREAD

**Issue by adamheine** [MehediH/TweetenSite#77]
Since there's currently no way to tell whether a tweet has been read or not, I use column clearing to make sure I'm not missing anything. Currently, however, this is a bit troublesome: I have to open the settings for each column, press Clear, then close the settings again.

Better would be a Clear button per column that requires only one click, or optionally being able to right-click on a column and select "Clear" from there.

A Clear All button would also be nice, to be able to clear all Tweets from all columns.

**Comment by MehediH** [comment]
This is something we can't do, ask the TweetDeck devs.
