### ISSUE TITLE
[Feature Request] "Jump to Earliest Tweet"

### ISSUE THREAD

**Issue by adamheine** [MehediH/TweetenSite#78]
Since there's currently no way to tell whether a tweet has been read or not, I use column clearing to make sure I'm not missing anything. One thing that would make this even easier is the ability to jump to the earliest tweet in a given column (currently, I have to scroll down -- sometimes several times as tweets load -- to get to my earliest unread tweet).

I'm not sure how this would work if it had to load tweets. There should probably be a maximum beyond which "Jump to Earliest Tweet" won't load tweets. Or maybe it could be "Go back X tweets" where X is some large number like 50 or 100.

**Comment by MehediH** [comment]
Not possible to implement this at the moment.
