### ISSUE TITLE
[Feature Request] Pop-up Notifications

### ISSUE THREAD

**Issue by adamheine** [MehediH/TweetenSite#79]
Currently, I'm not getting any notifications when Tweeten is out-of-focus, minimized, or in the System Tray. Not sure why that is.

Regardless, it would be extremely useful (ahem, to me) if new tweets appeared in a small window in the corner of the screen, so that I wouldn't even have to maximize Tweeten in order to read them.

**Comment by MehediH** [comment]
This is coming soon.
