### ISSUE TITLE
[Feature Request] Adding user mutes to Tweeten

### ISSUE THREAD

**Issue by InTheMoment** [MehediH/TweetenSite#80]
Recently Twitter/TweetDeck was "improving" their functionality (or so they claim) by making user mutes cross-platform between the native Twitter and TweetDeck. When you're muting a user on Twitter they are supposedly also muted on TweetDeck.

While that might be the case for some aspects (although there are users on twitter complaining that these muted users also show up in their mentions and elsewhere; I can't speak to that personally), it definitely has one HUGE downside. Muted users will now show up again in search. 

This is a big problem for me personally but I suspect also others. I'm not sure if you even can add a mute users feature to Tweeten or if it's native TD functionality but it would be a great enhancement to Tweeten imo. It's sort of a display functionality so I thought I'll give it a shot. You can only add so many user names in the exclude of the search string. 

That original TweetDeck-wide user mute was very powerful and now it isn't anymore.

**Comment by MehediH** [comment]
TweetDeck needs to add it, we can't do anything here.
