### ISSUE TITLE
Application crashes on receipt of mention/notification

### ISSUE THREAD

**Issue by RonnyTNL** [MehediH/TweetenSite#85]
I have an occasional crashing Tweeten application on Windows x64 when receiving mention or notification updates. Both have sound and desktop notifications enabled.

Doesnt' seem to pass postmortem debugger.

**Comment by RonnyTNL** [comment]
running tweeten in windbg results in to this...

(65c.2094): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for electron.exe - 
0000009d`078c2640 90              nop

**Comment by RonnyTNL** [comment]
It seems related to the 'Alert' setting 'sound/desktop notifications'
Switching these off seems to be more stable.

**Comment by RonnyTNL** [comment]
oeps, should not have been closed.

**Comment by MehediH** [comment]
Weird, I am rebuilding the app from ground-up so this should be fixed by then :)
