### ISSUE TITLE
On launching the app, a download pop-up always appears

### ISSUE THREAD

**Issue by Upperholme** [MehediH/TweetenSite#86]
When I launch Tweeten (version 0.36.5) on Mac OSX, a large blue box with no content appears, with two links : "Download Now" and "Download Later". Download Now simply appears to download the same version of the software, whilst Download Later closes the box. 
To be of use, this box should a) presumably have some content in addition to the two links, and b) assuming that it is designed to enable me to keep up to date, probably only appear when a new version is available for download.

**Comment by MehediH** [comment]
It's a new update notification :)
