### ISSUE TITLE
Minimize window when clicking link

### ISSUE THREAD

**Issue by bkesner** [MehediH/TweetenSite#87]
Is there anyway to not have the toggle always on top?  Would like tweeten window to minimize when clicking url in tweet.

Thanks,

Bart

**Comment by MehediH** [comment]
You can disable this from the context menu.

**Comment by bkesner** [comment]
Can you be more specific please as to where/how that is accomplished?  I
don't see a way to disable "Toggle always on top"

Thanks,

Bart



Barton D. Kesner
c 816.853.5634 w linkedin.com/in/bartkesner

**Comment by MehediH** [comment]
Right click anywhere in the app > Toggle always on top

**Comment by bkesner** [comment]
And when I  do that it still says "Toggle always on top".  It doesn't
change - it stayings in that setting.



Barton D. Kesner
c 816.853.5634 w linkedin.com/in/bartkesner

**Comment by MehediH** [comment]
Delete the Tweeten folder from %appdata% and reinstall the app.

**Comment by bkesner** [comment]
Still have the problem...I've uninstalled the app and deleted %appdata% and
it still stays in Toggle always on top.

Thanks.



Barton D. Kesner
c 816.853.5634 w linkedin.com/in/bartkesner
