### ISSUE TITLE
Crash creates javascript error, making Tweeten impossible to open

### ISSUE THREAD

**Issue by mmasnick** [MehediH/TweetenSite#88]
So, Tweeten crashed for me overnight, and when I went to reopen it this morning I get the following javascript error: 
![tweeten javascript error](https://cloud.githubusercontent.com/assets/19934997/19394594/a56cfe36-91ee-11e6-8d77-201886c8edce.png)

And then the app refuses to open no matter what I do.  I tried uninstalling and reinstalling, same problem.  I tried clearing out a bunch of stuff and restarting the computer.  I tried installing again from the Windows store.  None of it changes that error message.  I'm kind of pulling out my hair as I use Tweeten basically every waking minute and now it won't work at all.

**Comment by EmuAGR** [comment]
This happened to me right now after a BSOD. Windows 7 x64.
