### ISSUE TITLE
[macOS] Fullscreen disabled on Sierra

### ISSUE THREAD

**Issue by yoannf** [MehediH/TweetenSite#89]
On macOS Sierra, fullscreen mode doesn't work anymore. _View > Toggle full screen_ does nothing. And the green button reverses to the old "maximize" mode.

![capture d ecran 2016-10-16 a 18 23 57](https://cloud.githubusercontent.com/assets/19262498/19418898/dfef01d6-93cd-11e6-8286-f4a7a7ea1a1b.png)

I believe the issue started with macOS Sierra, though I'm not 100% sure.
With Tweeten 3.3.1

**Comment by pighair** [comment]
I started using Tweeten today and I have same issue. I also use MacOS Sierra

**Comment by MehediH** [comment]
Fixed on Tweeten 2.
