### ISSUE TITLE
Memory leak bug

### ISSUE THREAD

**Issue by jamacanbacn** [MehediH/TweetenSite#9]
When awaking my computer from sleep (Tweeten was minimized) and after booting tweeten was almost using a gb of ram. Will attach screenshot and can provide more info (just don't really know what info you guys need)
![memory](https://cloud.githubusercontent.com/assets/5510965/14023217/c174083e-f1b9-11e5-97ad-4666c9851ef6.png)

**Comment by snapzoom** [comment]
Also me too ..And I wonder why four Tweeten ?
![memoy](https://cloud.githubusercontent.com/assets/18668219/14800381/f35c5fe6-0b49-11e6-84aa-314fc4b92a72.PNG)

**Comment by MehediH** [comment]
Fixed.
