### ISSUE TITLE
Text in Activity Column

### ISSUE THREAD

**Issue by bkesner** [MehediH/TweetenSite#92]
The text of tweets is greyed out in the activity column making it more difficult to read.  That same text is not greyed out in Tweet Deck.  Please update to appear the same as in the other columns.  
![2016-10-21](https://cloud.githubusercontent.com/assets/22643146/19604339/6ea3ec7a-977a-11e6-9460-492d22266773.png)
Thanks.

**Comment by MehediH** [comment]
The light theme was never completed since not a lot of users use this feature. Will fix in the future.
