### ISSUE TITLE
[Feature Request] Color options

### ISSUE THREAD

**Issue by Stanzilla** [MehediH/TweetenSite#94]
Being able to change colors, text and background would be nice. as a bonus, the Windows 10 accent color is available via (recently added) Electron api, see http://electron.atom.io/docs/all/#event-accent-color-changed-windows for example.

Could be used to automatically color links by accent color kinda like MetroTwit

**Comment by MehediH** [comment]
I am considering adding this but will be quite annoying as Electron doesn't have an API to change the color of the titlebar (want to offer the same experience throughout the app, not just some parts)

**Comment by Stanzilla** [comment]
Yeah I read https://github.com/electron/electron/issues/4856

Looks like the only option to get that is by building your own title bar and hiding the native one.

**Comment by MehediH** [comment]
We actually had a custom titlebar in the past, but had some issues with it for multi-monitors.

**Comment by Stanzilla** [comment]
Pretty sure I even reported those problems back then, it was bleeding over to another monitor when maximized, could have been a Electron issue that is now fixed though as it currently works for apps that are doing it, tested with Discord.

**Comment by MehediH** [comment]
Will try it out soontm.

**Comment by MehediH** [comment]
Alright so I don't think I am gonna add this to the app. For one, there isn't any efficient method of compiling SASS on Electron. Plus, injecting CSS into `<webview>` using Electron is quite a messy process. I will have to figure out a way of doing this with pure CSS but it'll be difficult for maintaining things like the hover colour of elements etc. 

Let me know if you have any idea about other methods of implementing this though.
